[package]
name = "kalendar-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono-tz.workspace = true

[lints]
workspace = true
